import { IMAGE_CDN_URL } from './config';
import blurMap from '@/data/generated/blur-map.json';

/**
 * Resolves an image path to the URL that should actually be requested.
 *
 * Local (default)  '/images/vehicles/eeco.jpg'  ->  '/images/vehicles/eeco.jpg'
 * With a CDN set   '/images/vehicles/eeco.jpg'  ->  'https://cdn.../images/vehicles/eeco.jpg'
 * Already absolute 'https://...'                ->  returned untouched
 *
 * So the JSON files never have to know where the files are hosted. Flip
 * NEXT_PUBLIC_IMAGE_CDN_URL in .env.local and every image moves at once.
 */
export function resolveImage(path) {
  if (!path) return PLACEHOLDER_IMAGE;
  if (/^(https?:)?\/\//i.test(path) || path.startsWith('data:')) return path;
  const clean = path.startsWith('/') ? path : `/${path}`;
  return IMAGE_CDN_URL ? `${IMAGE_CDN_URL}${clean}` : clean;
}

export const PLACEHOLDER_IMAGE = '/images/placeholder.jpg';

/** Flat grey, used when an image has no generated preview yet. */
export const FALLBACK_BLUR =
  'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4IiBoZWlnaHQ9IjgiPjxyZWN0IHdpZHRoPSI4IiBoZWlnaHQ9IjgiIGZpbGw9IiNlNWUzZWQiLz48L3N2Zz4=';

/**
 * Real 16px-wide preview of the photo, generated by `npm run images`.
 * Falls back to flat grey for any image that hasn't been through the script.
 */
export function blurFor(path) {
  return blurMap[path] || FALLBACK_BLUR;
}

/**
 * Default `sizes` strings. These tell the browser how wide the image will
 * actually be displayed, so it downloads a 400px file on a phone instead of a
 * 1400px one. Getting these wrong is the single most common cause of a slow
 * image-heavy page.
 */
export const SIZES = {
  card: '(max-width: 640px) 88vw, (max-width: 1024px) 45vw, 300px',
  carousel: '(max-width: 640px) 80vw, (max-width: 1024px) 45vw, 290px',
  half: '(max-width: 768px) 100vw, 50vw',
  full: '100vw',
  wide: '(max-width: 1024px) 100vw, 640px',
  thumb: '(max-width: 640px) 45vw, 240px',
  logo: '180px',
};
