import Image from 'next/image';
import clsx from '@/lib/clsx';
import { resolveImage, blurFor, SIZES } from '@/lib/images';

/**
 * Thin wrapper over next/image so that:
 *  - every path runs through resolveImage() (local today, CDN tomorrow)
 *  - the blur placeholder generated by `npm run images` is used automatically
 *  - alt text is never accidentally skipped
 *
 * Use `fill` inside a parent with a fixed aspect ratio. Every card on this site
 * does that, which is why nothing jumps around while images load.
 */
export default function SmartImage({
  src,
  alt,
  fill = true,
  width,
  height,
  sizes = SIZES.card,
  className,
  wrapperClassName,
  priority = false,
  quality = 74,
  ...props
}) {
  const url = resolveImage(src);
  const blurDataURL = blurFor(src);

  if (!fill) {
    return (
      <Image
        src={url}
        alt={alt || ''}
        width={width}
        height={height}
        sizes={sizes}
        quality={quality}
        priority={priority}
        placeholder="blur"
        blurDataURL={blurDataURL}
        className={className}
        {...props}
      />
    );
  }

  return (
    <div className={clsx('relative overflow-hidden bg-ink/5', wrapperClassName)}>
      <Image
        src={url}
        alt={alt || ''}
        fill
        sizes={sizes}
        quality={quality}
        priority={priority}
        placeholder="blur"
        blurDataURL={blurDataURL}
        className={clsx('object-cover', className)}
        {...props}
      />
    </div>
  );
}
